//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairSalonWeb.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HairSalonWebDataBaseEntities : DbContext
    {
        public HairSalonWebDataBaseEntities()
            : base("name=HairSalonWebDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<IncomeMaterial> IncomeMaterial { get; set; }
        public virtual DbSet<IncomeMaterialBody> IncomeMaterialBody { get; set; }
        public virtual DbSet<IncomeMaterialHead> IncomeMaterialHead { get; set; }
        public virtual DbSet<MaterialType> MaterialType { get; set; }
    }
}
