//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairSalonWeb.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeMaterialHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomeMaterialHead()
        {
            this.IncomeMaterial = new HashSet<IncomeMaterial>();
        }
    
        public int IncomeMaterialHeadId { get; set; }
        public int InvoiceNumber { get; set; }
        public System.DateTime IncomeDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeMaterial> IncomeMaterial { get; set; }
    }
}
