//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairSalonWeb.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeMaterialBody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomeMaterialBody()
        {
            this.IncomeMaterial = new HashSet<IncomeMaterial>();
        }
    
        public int IncomeMaterialBodyId { get; set; }
        public string Name { get; set; }
        public decimal Count { get; set; }
        public decimal PurchaseCost { get; set; }
        public decimal RetailCost { get; set; }
        public int MaterialTypeId { get; set; }
        public int BrandId { get; set; }
    
        public virtual Brand Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncomeMaterial> IncomeMaterial { get; set; }
        public virtual MaterialType MaterialType { get; set; }
    }
}
